# .air.toml
# Air configuration file
# For more information, see https://github.com/cosmtrek/air

root = "."
tmp_dir = "tmp"

[build]
# 监听的文件扩展名
include_ext = ["go", "tpl", "tmpl", "html"]
# 忽略的文件目录
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
# 监听的文件目录
include_dir = ["internal", "api", "cmd", "configs", "pkg"]
# 忽略的文件路径
exclude_file = []
# 监听的文件路径
include_file = []
# 构建命令
cmd = "go build -v -o ./tmp/main ./cmd/server"
# 构建后运行的命令
bin = "./tmp/main"
# 构建后延迟运行的时间（毫秒）
delay = 1000
# 构建失败时停止运行
stop_on_error = false
# 发送中断信号而不是杀死进程
send_interrupt = false
# 构建日志前缀
log = "build"
# 构建时是否启用颜色输出
color = true
# 构建参数
args_bin = []
# 构建错误日志文件
err_log = "tmp/build-errors.log"

[log]
# 日志级别，可以是 debug, info, warn, error
level = "debug"
# 日志输出时间格式
time = true

[color]
# 颜色输出设置
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# 杂项设置
# 清理临时文件
clean_on_exit = true
# 启用调试模式
debug = false