# 应用基础配置
app:
  name: "demo-service"
  env: "dev"  # 环境：dev(开发)、test(测试)、prod(生产)
  version: "1.0.0"

# 服务器配置
server:
  port: 8080
  timeout: 30  # 超时时间(秒)
  read_timeout: 15
  write_timeout: 15

# 数据库配置（多类型支持）
database:
  # MySQL配置
  mysql:
    driver: "mysql"
    dsn: "root:123456@tcp(127.0.0.1:3306)/go_test?charset=utf8mb4&parseTime=True&loc=Local"
    max_open_conns: 100        # 最大打开连接数
    max_idle_conns: 20         # 最大空闲连接数
    conn_max_lifetime: 3600    # 连接最大存活时间(秒)
    conn_max_idle_time: 1800   # 连接最大空闲时间(秒)
    log_mode: true             # 是否开启SQL日志
    slow_threshold: 500        # 慢查询阈值(毫秒)

  # PostgreSQL配置
  postgres:
    driver: "postgres"
    dsn: "host=127.0.0.1 port=5432 user=postgres password=password dbname=demo_db sslmode=disable"
    max_open_conns: 50
    max_idle_conns: 10
    conn_max_lifetime: 3600
    conn_max_idle_time: 1800

  # SQLite配置（适合轻量应用）
  sqlite:
    driver: "sqlite3"
    dsn: "./data/demo.db"
    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: 0       # SQLite不支持连接存活时间限制，设为0

  # MongoDB配置（文档数据库）
  mongodb:
    uri: "mongodb://root:password@127.0.0.1:27017/demo_db?authSource=admin"
    database: "demo_db"
    max_pool_size: 20          # 连接池大小
    min_pool_size: 5
    timeout: 10                # 连接超时(秒)

# Redis配置（缓存/队列）
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 2
  idle_timeout: 300           # 空闲连接超时(秒)
  read_timeout: 3
  write_timeout: 3

# Zap日志配置
log:
  level: "info"  # debug/info/warn/error/dpanic/panic/fatal
  format: "console"  # console/json
  output_path: "logs/app.log"  # 日志输出文件
  max_size: 100  # 单个日志文件大小(MB)
  max_backup: 10  # 最大备份数
  max_age: 7  # 最大保留天数
  compress: false  # 是否压缩    