# 开发环境配置
server:
  port: 8080
  mode: debug
  read_timeout: 60
  write_timeout: 60
  max_header_mb: 1

# 数据库配置
database:
  driver: mysql
  dsn: "root:123456@tcp(localhost:3306)/go_demo?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 3600
  conn_max_idle_time: 1800
  log_mode: true
  slow_threshold: 200

# JWT配置
jwt:
  secret_key: "wVvHx4e0ZvJ8a9d6r5t3yu0i9o7p6y4t3r2e1w2q3s4d5f6"
  access_expire: 3600
  refresh_expire: 604800
  issuer: "go_demo"

# 日志配置
log:
  level: debug
  format: json
  output_path: "./logs/app.log"
  req_log_path: "./logs/request.log"
  max_size: 100
  max_backup: 10
  max_age: 30
  compress: true

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  
  # 限流配置
rate_limiter:
  enabled: true
  global_limit: 1000    # 全局限流，单位：请求/秒
  user_limit: 100       # 用户限流，单位：请求/分钟
  ip_limit: 200         # IP限流，单位：请求/分钟
  window: 60            # 滑动窗口大小，单位：秒
  algorithm: sliding    # 算法类型：fixed, sliding

# 熔断器配置
circuit_breaker:
  enabled: true
  max_requests: 5          # 触发熔断检查的最小请求数
  half_open_max_requests: 3 # 半开状态最大请求数
  timeout: 5                # 熔断器打开后的超时时间，单位：秒
  error_threshold: 0.5       # 错误率阈值（0-1之间）